# Generated by Django 5.2.4 on 2026-06-17 17:16

import django.db.models.deletion
import mptt.fields
import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('cities_light', '0012_city_translations_country_translations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('price', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('stock', models.IntegerField()),
                ('category', mptt.fields.TreeForeignKey(default=product.models.get_default_category, on_delete=django.db.models.deletion.PROTECT, to='categories.categories', verbose_name='category')),
                ('origin_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(upload_to=product.models.product_image_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
            options={
                'verbose_name_plural': 'product images',
                'db_table': 'product_images',
            },
        ),
    ]
