# Generated by Django 5.2.4 on 2025-12-23 00:37

import django.db.models.deletion
import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0012_city_translations_country_translations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to=product.models.product_image_path)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('stock', models.IntegerField()),
                ('origin_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country')),
            ],
        ),
    ]
