# Generated by Django 5.2.4 on 2026-01-11 18:54

import django.db.models.deletion
import mptt.fields
import product.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('product', '0002_remove_product_image_productimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=mptt.fields.TreeForeignKey(default=product.models.get_default_category, on_delete=django.db.models.deletion.PROTECT, to='categories.categories', verbose_name='category'),
        ),
    ]
