# Generated by Django 5.2.4 on 2026-06-17 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attributes', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attributes', to='product.product'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attributes.attributevalue'),
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('category', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together={('attribute', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together={('product', 'attribute')},
        ),
    ]
